Remove completely top-level Java CordaCaplet unit tests causing consistent TC failure on Azure VMs:
 java.security.NoSuchAlgorithmException: no such algorithm: NONEwithEdDSA for provider BC