Correct unchecked cast call (#1973)
Or else NodeExplorer will not start due to exception:
java.lang.ClassCastException: net.corda.core.contracts.StateAndRef cannot be cast to java.lang.Void
	at net.corda.client.jfx.model.ContractStateModel$Companion.filterCashStateAndRefs(ContractStateModel.kt:43)
	at net.corda.client.jfx.model.ContractStateModel$Companion.access$filterCashStateAndRefs(ContractStateModel.kt:38)
	at net.corda.client.jfx.model.ContractStateModel$cashStatesDiff$1.call(ContractStateModel.kt:29)
	at net.corda.client.jfx.model.ContractStateModel$cashStatesDiff$1.call(ContractStateModel.kt:22)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
	at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:304)
	at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:219)
	at rx.subjects.PublishSubject.onNext(PublishSubject.java:72)