Remove usage of JavaScript within log4j2.xml to prevent JVM attempt to load private scripting package:
Execution worker for ':' INFO Cannot initialize scripting support because this JRE does not support it. java.lang.NoClassDefFoundError: javax/script/ScriptEngineManager
at org.apache.logging.log4j.core.script.ScriptManager.<init>(ScriptManager.java:69)
caused by JavaScript embedded in log4j.xml (remove as not required)