ENT-14431: Replace dots with slashes when extracting a missing class in NoClassDefFoundError (#8011)
Replace dots with slashes in NoClassDefFoundError so that the regex
pattern can extract the missing class.
See https://github.com/corda/corda/pull/7996