CORDA-1042: Change the way how Jolokia library located on the classpath so that it work on Windows (#2817)
Old code failed with:
```
11:34:01.536 [main] ERROR net.corda.node.internal.Node - Exception during node startup
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program%20Files/JetBrains/IntelliJ%20IDEA%20Community%20Edition%202017.3.1/lib/idea_rt.jar
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[?:1.8.0_144]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[?:1.8.0_144]
	at java.nio.file.Paths.get(Paths.java:84) ~[?:1.8.0_144]
	at net.corda.node.utilities.JVMAgentRegistry.resolveAgentJar(JVMAgentRegistry.kt:46) ~[classes/:?]
	at net.corda.node.internal.AbstractNode.initialiseJVMAgents(AbstractNode.kt:785) ~[classes/:?]
	at net.corda.node.internal.AbstractNode.start(AbstractNode.kt:199) ~[classes/:?]
	at net.corda.node.internal.Node.start(Node.kt:335) ~[classes/:?]
	at net.corda.node.internal.NodeStartup.startNode(NodeStartup.kt:146) ~[classes/:?]
	at net.corda.node.internal.NodeStartup.run(NodeStartup.kt:120) [classes/:?]
	at net.corda.node.Corda.main(Corda.kt:16) [classes/:?]
```