CORDA-2030 - ensure the correct kotlin runtime library is used to resolve `AutoCloseable` Fixes compatibility issue surfaced as "java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt"