CORDA-2030 - ensure the correct kotlin runtime library is used to resolve `AutoCloseable` (#4028)
Fixes compatibility issue surfaced as "java.lang.NoClassDefFoundError: kotlin/jdk7/AutoCloseableKt"